name: city_info_guide
description: City information and guide app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  flutter_typeahead: ^4.0.0
  dio: ^4.0.6
  intl: ^0.17.0
  get_it: ^7.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  auto_route: ^4.0.1
  flutter_native_splash: ^2.2.3
  cached_network_image: ^3.2.1
  geolocator: ^8.2.1
  shimmer: ^2.0.0
  mockito: ^5.2.0
  http_mock_adapter: ^0.3.3
  equatable: ^2.0.3
  dartz: ^0.10.1
  lottie: ^1.3.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  yandex_mapkit: ^3.0.0
  flutter_launcher_icons: ^0.9.3
  toggle_switch: ^2.0.1
  easy_localization: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0
  flutter_gen_runner: ^4.3.0
  test: ^1.21.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  color: "#525814"
  image: assets/images/bird.png

flutter_gen:
  output: lib/app/assets